# Generated by Django 4.1 on 2024-03-10 02:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MERCADO', 'Mercado'), ('CASA', 'Casa')], default='', max_length=100, verbose_name='Tipo')),
                ('value', models.FloatField(default=0.0, verbose_name='Valor')),
                ('voucher', models.ImageField(blank=True, upload_to='images/', verbose_name='Comprovante')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('divided_accounts', models.ManyToManyField(related_name='divided_spending_set', to='accounts.user', verbose_name='Conta(s) Dividida(s)')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_spending_set', to='accounts.user', verbose_name='Regitrador')),
            ],
        ),
        migrations.CreateModel(
            name='Spending_Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MERCADO', 'Mercado'), ('CASA', 'Casa')], default='', max_length=100, verbose_name='Status')),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='Conta Relacionada')),
                ('spending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spending.spending', verbose_name='Gasto Relacionado')),
            ],
        ),
    ]
